---
# ====================
#    Configuration 
# ====================

# Set to True to take xp straight to inventory when breaking a block
auto-exp-block: true

# If you set to true add World's where plugin work's
block-exp-worlds:
  - MinaPvP # Example
  - world # Example

# Set to True to take xp straight to Inventory when kill another player
auto-kill-exp: true

# If you set to true add World's where plugin work's
kill-exp-worlds: 
  - ArenaPvP #Example
  - KitPvP #Example
...
